Controllers/MerchanController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;

namespace MVCMerchandising.Controllers
{
    public class MerchanController : Controller
    {
        // GET: /HelloWorld/
        public IActionResult Index()

        {

            return View();

        }


        public IActionResult Tienda(string name, int numTimes = 1)

        {

            ViewData["Message"] = "Hello " + name;

            ViewData["NumTimes"] = numTimes;


            return View();

        }
        public IActionResult Info()

        {

            return View();

        }
    }
}

Controllers/MerchandisingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCMerchandising.Data;
using MVCMerchandising.Models;

namespace MVCMerchandising.Controllers
{
    public class MerchandisingsController : Controller
    {
        private readonly MVCMerchandisingContext _context;

        public MerchandisingsController(MVCMerchandisingContext context)
        {
            _context = context;
        }

        // GET: Merchandisings
        public async Task<IActionResult> Index(string MerchanTalles, string SearchString)

        {

            IQueryable<string> genreQuery = from m in _context.Merchandising

                                            orderby m.Talles

                                            select m.Talles;


            var Product = from m in _context.Merchandising

                          select m;


            if (!string.IsNullOrEmpty(SearchString))

            {

                Product = Product.Where(s => s.Producto.Contains(SearchString));

            }


            if (!string.IsNullOrEmpty(MerchanTalles))

            {

                Product = Product.Where(x => x.Talles == MerchanTalles);

            }


            var ProductGenreVM = new MerchanTalleViewModel

            {

                Talles = new SelectList(await genreQuery.Distinct().ToListAsync()),

                Productos = await Product.ToListAsync()

            };


            return View(ProductGenreVM);

        }

        // GET: Merchandisings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var merchandising = await _context.Merchandising
                .FirstOrDefaultAsync(m => m.Id == id);
            if (merchandising == null)
            {
                return NotFound();
            }

            return View(merchandising);
        }

        // GET: Merchandisings/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Merchandisings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Producto,Talles,Descripcion,Precio,Colores,Imagen")] Merchandising merchandising)
        {
            if (ModelState.IsValid)
            {
                _context.Add(merchandising);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(merchandising);
        }

        

        // GET: Merchandisings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var merchandising = await _context.Merchandising.FindAsync(id);
            if (merchandising == null)
            {
                return NotFound();
            }
            return View(merchandising);
        }

        // POST: Merchandisings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Producto,Talles,Descripcion,Precio,Colores,Imagen")] Merchandising merchandising)
        {
            if (id != merchandising.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(merchandising);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MerchandisingExists(merchandising.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(merchandising);
        }

        // GET: Merchandisings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var merchandising = await _context.Merchandising
                .FirstOrDefaultAsync(m => m.Id == id);
            if (merchandising == null)
            {
                return NotFound();
            }

            return View(merchandising);
        }

        // POST: Merchandisings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var merchandising = await _context.Merchandising.FindAsync(id);
            _context.Merchandising.Remove(merchandising);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MerchandisingExists(int id)
        {
            return _context.Merchandising.Any(e => e.Id == id);
        }

        public async Task<IActionResult> AlCarrito([Bind("Id,Productos,Talles,Descripcion,Precio")] Producto a)
        {
            if (ModelState.IsValid)
            {
                _context.Add(a);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(AlCarrito));
            }
            return View(a);
        }
        public IActionResult Carrito()

        {

            return View();

        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="utf-8" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewData["Title"] - Merchandising</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <link rel="stylesheet" href="~/css/site.css" />

</head>

<body style="background-image: linear-gradient(to bottom, white, pink, #EFA5D0, #A76DFC);">

    <header>

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light box-shadow mb-3">

            <div class="container">
                <img src="https://play-lh.googleusercontent.com/XB2KVHIkLzmtSuNarhmTKmH9M2orc5FFvopF507YQjoPfpmlHTcwii04sSJy4HM6408=w240-h480-rw" width=70 height=70 alt="imgsf"/>
                <button class="btn bg-light">
                   <a class="navbar-brand" asp-controller="Home" asp-action="Index">Inicio</a> 
                </button>
                <button class="btn bg-light">
                   <a class="navbar-brand" asp-controller="Merchandisings" asp-action="Index">Merchandising</a>
                </button>
                <button class="btn bg-light">
                   <a class="navbar-brand" asp-controller="Home" asp-action="Privacy">Contacto</a>
                </button>
                <button class="btn bg-light">
                   <a class="navbar-brand" asp-controller="Merchandisings" asp-action="Carrito">Carrito</a>
                </button>
                
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">

                </div>

            </div>

        </nav>

    </header>

    <div class="container">

        <main role="main" class="pb-3">

          @RenderBody()

        </main>

    </div>


    <footer class="border-top footer text-muted">

        <div class="container">

            &copy; 2022 - RemeranimeJAJASALU2 - <a asp-controller="Merchan" asp-action="Info">Informacion</a>

        </div>

    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)

</body>

</html>